CREATE DATABASE QLBH

USE QLBH

http://www.hongyen.vn/

--CREATE TABLE ABSTRACT_MODEL
--(
--	ID VARCHAR(10) NOT NULL PRIMARY KEY,
--	SLUG VARCHAR(256) NULL,
--	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
--	CREATED_BY NVARCHAR(100),
--	MODIFIED_AT DATETIME,
--	MODIFIED_BY NVARCHAR(100),
--	DELETED_AT DATETIME,
--	IS_DELETED BIT DEFAULT 0,
--	[STATUS] BIT DEFAULT 1,
--)

CREATE TABLE CATEGORY
(
	SLUG VARCHAR(256) NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY NVARCHAR(100),
	MODIFIED_AT DATETIME,
	MODIFIED_BY NVARCHAR(100),
	DELETED_AT DATETIME,
	IS_DELETED BIT DEFAULT 0,
	[STATUS] BIT DEFAULT 1,

	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	NAME NVARCHAR(256),
	[IMAGE] VARCHAR(256),
	PARENT_ID INT NOT NULL
)

CREATE TABLE PRODUCT
(
	SLUG VARCHAR(256) NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY NVARCHAR(100),
	MODIFIED_AT DATETIME,
	MODIFIED_BY NVARCHAR(100),
	DELETED_AT DATETIME,
	IS_DELETED BIT DEFAULT 0,
	[STATUS] BIT DEFAULT 1,

	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	NAME NVARCHAR(256),
	QUANTITY INT,
	PRICE FLOAT,
	[DESCRIPTION] NVARCHAR(512),
	[IMAGE] VARCHAR(256),
	CATEGORY_ID VARCHAR(10) NOT NULL,
)

CREATE TABLE [USER]
(
	SLUG VARCHAR(256) NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY NVARCHAR(100),
	MODIFIED_AT DATETIME,
	MODIFIED_BY NVARCHAR(100),
	DELETED_AT DATETIME,
	IS_DELETED BIT DEFAULT 0,
	[STATUS] BIT DEFAULT 1,

	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	FULLNAME NVARCHAR(64),
	USERNAME NVARCHAR(128) NOT NULL,
	[PASSWORD] VARCHAR(128) NOT NULL,
	AVATAR VARCHAR(512),
	ROLE_ID VARCHAR(10) NOT NULL
)

CREATE TABLE [ROLE]
(
	SLUG VARCHAR(256) NULL,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY NVARCHAR(100),
	MODIFIED_AT DATETIME,
	MODIFIED_BY NVARCHAR(100),
	DELETED_AT DATETIME,
	IS_DELETED BIT DEFAULT 0,
	[STATUS] BIT DEFAULT 1,

	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	NAME NVARCHAR(64) NOT NULL UNIQUE,
	CODE VARCHAR(64) NOT NULL UNIQUE,
)

--CREATE TABLE NEWS
--(
--	SLUG VARCHAR(256) NULL,
--	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
--	CREATED_BY NVARCHAR(100),
--	MODIFIED_AT DATETIME,
--	MODIFIED_BY NVARCHAR(100),
--	DELETED_AT DATETIME,
--	IS_DELETED BIT DEFAULT 0,
--	[STATUS] BIT DEFAULT 1,

--	ID VARCHAR(10) NOT NULL PRIMARY KEY,
--	TITLE NVARCHAR(255) NULL,
--	THUMBNAIL NVARCHAR(255) NULL,
--	SHORT_DESCRIPTION TEXT NULL,
--	CONTENT TEXT NULL,
--	CATEGORY_ID BIGINT NOT NULL,
--)

--CREATE TABLE COMMENT
--(
--	SLUG VARCHAR(256) NULL,
--	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
--	CREATED_BY NVARCHAR(100),
--	MODIFIED_AT DATETIME,
--	MODIFIED_BY NVARCHAR(100),
--	DELETED_AT DATETIME,
--	IS_DELETED BIT DEFAULT 0,
--	[STATUS] BIT DEFAULT 1,

--	ID VARCHAR(10) NOT NULL PRIMARY KEY,
--	CONTENT TEXT NOT NULL,
--	[USER_ID] BIGINT NOT NULL,
--	NEWS_ID BIGINT NOT NULL,
--)

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
ON UPDATE CASCADE ON DELETE CASCADE

ALTER TABLE [USER]
ADD CONSTRAINT FK_USER_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES [ROLE](ID)
ON DELETE CASCADE ON UPDATE CASCADE

INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0000', N'Điện thoại', '')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0001', N'SAMSUNG', 'DM0001')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0002', N'NOKIA', 'DM0001')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0003', N'OPPO', 'DM0001')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0004', N'XIAOMI', 'DM0001')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0005', N'VSMART', 'DM0001')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0006', N'APPLE', 'DM0001')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0100', N'REALME', 'DM0001')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0200', N'Đồng hồ thông minh', '')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0300', N'Máy tính bàn', '')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0400', N'Máy tính bản', '')
INSERT INTO CATEGORY(ID, NAME, PARENT_ID) VALUES ('DM0500', N'Thiết bị khác', '')

INSERT INTO PRODUCT(ID, NAME, QUANTITY, PRICE, IMAGE, CATEGORY_ID) VALUES('SP01', N'iPhone 12 Pro Max 512GB - Chính Hãng VN/A', 100, 36990000, 'http://www.hongyen.vn/uploads/productgalleries/bf094c198be03b1116659de1770e97b7.png', 'DM0001')
INSERT INTO PRODUCT(ID, NAME, QUANTITY, PRICE, IMAGE,CATEGORY_ID) VALUES('SP02', N'iPhone 12 Pro 512GB - Chính Hãng VN/A', 100, 33890000, 'http://www.hongyen.vn/uploads/productgalleries/b6c42a0c2eb6da0ed21ea94810e8bfc9.jpg', 'DM0001')
INSERT INTO PRODUCT(ID, NAME, QUANTITY, PRICE, IMAGE,CATEGORY_ID) VALUES('SP03', N'iPhone 12 Pro Max 256GB - Chính Hãng VN/A', 100, 31700000, 'http://www.hongyen.vn/uploads/productgalleries/92718a953a8b540bb9b51486e784601a.png', 'DM0001')
INSERT INTO PRODUCT(ID, NAME, QUANTITY, PRICE, IMAGE,CATEGORY_ID) VALUES('SP04', N'iPhone 12 Pro Max 128GB - Chính Hãng VN/A', 100, 28850000, 'http://www.hongyen.vn/uploads/productgalleries/334b8175059ffa2c07c223b5e410d3e4.png', 'DM0001')
INSERT INTO PRODUCT(ID, NAME, QUANTITY, PRICE, IMAGE,CATEGORY_ID) VALUES('SP05', N'iPhone 12 Pro 128GB - Chính Hãng VN/A', 100, 28900000, 'http://www.hongyen.vn/uploads/productgalleries/52e388e92e4adf383c1ffaa2064620bf.png', 'DM0001')
INSERT INTO PRODUCT(ID, NAME, QUANTITY, PRICE, IMAGE,CATEGORY_ID) VALUES('SP06', N'iPhone 12 256GB - Chính Hãng VN/A', 100, 26500000, 'http://www.hongyen.vn/uploads/productgalleries/4a00ba23d99aa807b16667dadb7d29ab.jpg', 'DM0001')
INSERT INTO PRODUCT(ID, NAME, QUANTITY, PRICE, IMAGE,CATEGORY_ID) VALUES('SP07', N'iPhone 12 128GB - Chính Hãng VN/A', 100, 23900000, 'http://www.hongyen.vn/uploads/productgalleries/463945d10a22530801b611b950ec23de.jpg', 'DM0001')
INSERT INTO PRODUCT(ID, NAME, QUANTITY, PRICE, IMAGE,CATEGORY_ID) VALUES('SP08', N'iPhone 12 64GB - Chính Hãng VN/A', 100, 21200000, 'http://www.hongyen.vn/uploads/productgalleries/f208324d67098e6316435fb4dddce4e2.png','DM0001')
INSERT INTO PRODUCT(ID, NAME, QUANTITY, PRICE, IMAGE, CATEGORY_ID) VALUES('SP09', N'iPhone 12 Pro Max 512GB - Chính Hãng VN/A', 100, 36990000, 'http://www.hongyen.vn/uploads/productgalleries/bf094c198be03b1116659de1770e97b7.png', 'DM0001')

INSERT INTO [ROLE](ID, NAME, CODE) VALUES ('Q0001', N'Quản trị', 'ADMIN')
INSERT INTO [ROLE](ID, NAME, CODE) VALUES ('Q0002', N'Khách hàng', 'CUSTOMER')
INSERT INTO [ROLE](ID, NAME, CODE) VALUES ('Q0003', N'Thành viên', 'MEMBER')

INSERT INTO [USER](ID, FULLNAME, USERNAME, [PASSWORD], AVATAR, ROLE_ID) VALUES ('ND0001', N'Nguyễn Sỹ Bảo', 'admin', '1', '', 'Q0001')
INSERT INTO [USER](ID, FULLNAME, USERNAME, [PASSWORD], AVATAR, ROLE_ID) VALUES ('ND0002', N'Nguyễn Văn Thanh', 'customer', '1', '', 'Q0002')
INSERT INTO [USER](ID, FULLNAME, USERNAME, [PASSWORD], AVATAR, ROLE_ID) VALUES ('ND0003', N'Nguyễn Lý Tử', 'member', '1', '', 'Q0003')

--SLUG VARCHAR(256) NULL,
--	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
--	CREATED_BY NVARCHAR(100),
--	MODIFIED_AT DATETIME,
--	MODIFIED_BY NVARCHAR(100),
--	DELETED_AT DATETIME,
--	IS_DELETED BIT DEFAULT 0,
--	[STATUS] BIT DEFAULT 1,

ALTER PROC INSERT_CATEGORY_1(@ID VARCHAR(10), @NAME NVARCHAR(256), @IMAGE VARCHAR(256), @PARENT_ID VARCHAR(10))
AS BEGIN
	INSERT INTO CATEGORY(ID, NAME, [IMAGE], PARENT_ID) VALUES (@ID, @NAME, @IMAGE, @PARENT_ID)
END

CREATE PROC INSERT_CATEGORY_2(@ID VARCHAR(10), @NAME NVARCHAR(256), @PARENT_ID VARCHAR(10), @CREATED_BY NVARCHAR(100), @STATUS BIT)
AS BEGIN
	INSERT INTO CATEGORY(ID, NAME, PARENT_ID, CREATED_BY, [STATUS]) VALUES (@ID, @NAME, @PARENT_ID, @CREATED_BY, @STATUS)
END

CREATE FUNCTION GENERATOR_SLUG
(   
    @str VARCHAR(100)
)
RETURNS VARCHAR(100)
AS
BEGIN
DECLARE @IncorrectCharLoc SMALLINT
SET @str = LOWER(@str)
SET @IncorrectCharLoc = PATINDEX('%[^0-9a-z ]%',@str)
WHILE @IncorrectCharLoc > 0
BEGIN
SET @str = STUFF(@str,@incorrectCharLoc,1,'')
SET @IncorrectCharLoc = PATINDEX('%[^0-9a-z ]%',@str)
END
SET @str = REPLACE(@str,' ','-')
RETURN @str +'-'+CAST((DATEDIFF(s, '1970-01-01 00:00:00', GETDATE())) AS VARCHAR(64))
END
